### ISSUE TITLE
Can't compile against new AGPL SeisComP: Seiscomp::Array’ has no member named ‘bytes’

### ISSUE THREAD

**Issue by luca-s** [swiss-seismological-service/scrtdd#28]
The code currently compiles only with SeisComp**3** Release **2018.327**.x series.
Since the API changed in the new SeisComP there is no way to make the same code compiles on both the previous and new versions so I will create a new branch soon for differentiate the releases.

Compilation logs:
```
[ 99%] Built target seiscomp3_rtddmsg
[ 99%] Building CXX object src/rtdd-addons/apps/scrtdd/CMakeFiles/scrtdd.dir/hdd/wfmngr.cpp.o
/home/centos/seiscomp3/src/rtdd-addons/apps/scrtdd/hdd/wfmngr.cpp: In static member function ‘static void Seiscomp::HDD::WfMngr::writeTrace(Seiscomp::GenericRecordCPtr, const string&)’:
/home/centos/seiscomp3/src/rtdd-addons/apps/scrtdd/hdd/wfmngr.cpp:877:57: error: ‘const class Seiscomp::Array’ has no member named ‘bytes’
int reclen = msRec.data()->size()*msRec.data()->bytes() + 64;
^
make[2]: *** [src/rtdd-addons/apps/scrtdd/CMakeFiles/scrtdd.dir/hdd/wfmngr.cpp.o] Error 1
make[1]: *** [src/rtdd-addons/apps/scrtdd/CMakeFiles/scrtdd.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by comoglu** [comment]
Hi Luca,
Actually the error message comes with the current seiscomp3 repository, not new SeisComP. I tried again to make sure that I am giving the right information to you.

![image](https://user-images.githubusercontent.com/8641736/81061525-d93e9b00-8f17-11ea-98e0-64c65dc38457.png)

**Comment by comoglu** [comment]
The compilation is OK when I remove rtdd-addons from the source directory

**Comment by luca-s** [comment]
Ah! Thanks for clarifying this. Can you tell me what brach/tag are you using for compilation (maybe are you using maste)? I tested only the old release 2018.327.x. Maybe the new one has the same changes as the new SeisComP. 

I am now making some changes, I'll update here when they are done and hopefully your issue will get fixed.

In the meanwhile, you could try the `build/jakarta/2018.327` branch (git checkout build/jakarta/2018.327) and that should work.

**Comment by comoglu** [comment]
This is the output if I used release p19, I will be trying p18 as well when I have time. 
![image](https://user-images.githubusercontent.com/8641736/81126446-a085dc80-8f7e-11ea-84d7-141d0d9cabd9.png)

**Comment by luca-s** [comment]
I pushed some commits that fix the compilation errors you encountered. If you update your scrtdd code it should compiles fine now.

**Comment by luca-s** [comment]
I forgot; p19 is fine, you don't need to try p18.

**Comment by comoglu** [comment]
Yep, I am able to compile it with branch 2018.327. I will be following the documentation to see how to use it within seiscomp3 when time allows me to do so.

**Comment by luca-s** [comment]
There is now a new branch [new_agpl_seiscomp](https://github.com/swiss-seismological-service/scrtdd/tree/new_agpl_seiscomp) that compiles the code agains the new SeisComP. I will merge it to master when the official launch of the AGPL SeisComP happens.
