### ISSUE TITLE
multi-event relocation: error in hypoDD.inp

### ISSUE THREAD

**Issue by rlmagnusson** [swiss-seismological-service/scrtdd#4]
After computing cross-correlations the call to `hypoDD` with the generated control file `hypoDD.inp` fails.

From output of `scrtdd --reloc-profile hengill100 -d $mainDB --debug`:

>00:20:21 [info] Working directory /home/testcomp/seiscomp3/var/lib/rtdd/hengill100/catalog
00:20:21 [info] Executing command: /bin/sh -c /home/testcomp/HYPODD/src/hypoDD/hypoDD hypoDD.inp >hypoDD.out 2>&1

this last call fails resulting in the output file `hypoDD.out` looking like this:
>STOP Program run aborted.
starting hypoDD (v1.3 - 11/2010)...          Tue Mar 17 14:09:46 2020
 >>> ERROR READING CONTROL PARAMETERS IN LINE           10
 hypoDD.src   

causing the next step to fail:
>00:20:21 [info] Loading catalog relocated by hypodd...
00:20:21 [error] Cannot relocate profile catalog: Cannot load hypodd relocated catalog file: /home/testcomp/seiscomp3/var/lib/rtdd/hengill100/catalog/hypoDD.reloc

and scrtdd to close.

**Comment by luca-s** [comment]
So it seems that HypoDD doesn't like your configuration file:

> ERROR READING CONTROL PARAMETERS IN LINE 10
> hypoDD.src

Have you looked at this line? Anything suspiciuous? 

You can also go into the working directory (if you enabled in scconfig to not delete the working files) and try modifying the configuration from there:

`
cd /home/testcomp/seiscomp3/var/lib/rtdd/hengill100/catalog
edit  hypoDD.inp
/home/testcomp/HYPODD/src/hypoDD/hypoDD hypoDD.inp
`
Can you also copy here the content of your HypoDD control file?

**Comment by luca-s** [comment]
Also, I forgot to highlight that scrtdd copies the HypoDD control file you configured to the working directory. While doing so, scrtdd replaces the input and output file names. So it would be worth it to double check the content of hypoDD.inp insidere the working directory to make sure scrtdd didn't make any damage to the file (in case I'll fix the bug)

**Comment by luca-s** [comment]
On a side note I saw that you used the ` --debug:` option. I would suggest the `--verbosity=3 --console=1` option instead, otherwise you get overwhelmed by the logs  and it becomes difficult to understand what scrtdd is doing. Just my 2 cents

**Comment by luca-s** [comment]
@rlmagnusson I believe I figured it out what the problem is. You are using HypoDD version 2.1b control file but you configured a HtpoDD version 1.3  executable

**Comment by rlmagnusson** [comment]
Yes that seems to be the case. I was able to relocate successfully using the recently added file data/hypoDD_MultiEvent_1.3.inp.
