### ISSUE TITLE
Documentation review

### ISSUE THREAD

**Issue by luca-s** [swiss-seismological-service/scrtdd#40]
The documentation needs to be reviewed and improved. This involves both the README and the [configuration parameters description](https://github.com/swiss-seismological-service/scrtdd/blob/master/apps/scrtdd/descriptions/scrtdd.xml)

Anything from syntax/grammar/spelling mistakes to broader changes is welcome.

**Comment by damb** [comment]
@luca-s, I can do that if it is ok for you.

**Comment by luca-s** [comment]
That would be great. if you can do it, that's great
