### ISSUE TITLE
Sclistorg doesn't work

### ISSUE THREAD

**Issue by Donavin97** [swiss-seismological-service/scrtdd#48]
Hello everyone.
I compiled scrtdd succesfully on Ubuntu20.04.1LTS with seiscomp4.5.0 and scrtdd1.3.2.
However I am trying to list origins for scrtdd to work on.
I get the following error.
terminate called after throwing an instance of 'Seiscomp::Core::DuplicateClassname'
  what():  CharArray
Aborted (core dumped)

How can I fix this?
Kind regards: Donavin.

**Comment by luca-s** [comment]
Hi @Donavin97.  How exactly are you running `sclistorg`? May I see the full command line and console output so that I can try to replicate the issue?

**Comment by Donavin97** [comment]
Hi there.
The issue was with my compilation of seiscomp not the scrtdd module.
I will keep this open incase I encounter any further errors.
I will post full outputs of the terminal when I try it out again.
Thanks for the very quick response.

**Comment by Donavin97** [comment]
Hi there, I have another issue, I am having trouble setting up scrtdd. Is there somewhere I can get a configuration file to edit according to my needs?
Thanks.

**Comment by luca-s** [comment]
What kind of issue are you experiencing?

**Comment by Donavin97** [comment]
I figured out the configuration file and have set it up. I am just wondering if the locator can work for a widely spaced network, or is this only suitable for local networks?

**Comment by luca-s** [comment]
It should work on  any kind of network. There is an initial clustering phase where separated events are grouped together, then each group is DD inverted independently.  We also tested the code on the full Switzerland region, so I don't foresee issues.

**Comment by Donavin97** [comment]
Thanks for all the help, I'll refine the parameters and use this awesome module for relocation.
Thanks to the developers for making available this project.
