### ISSUE TITLE
Unassociated origins: --xmlout

### ISSUE THREAD

**Issue by cjhopp** [swiss-seismological-service/scrtdd#59]
Hi Luca,

Another quick question: When using --xmlout and opening the resulting file in scolv, for example, I see only unassociated origins. Reading the file with obspy returns a catalog with no events. The output shows what I think are reasonable relocations and there are no obvious errors.

Is this expected? Or does it suggest that A) my parameters are improper in the relocation and scrtdd won't include them because of a quality threshold B) I still need to run another command (scevent? or a flag in scrtdd?) to return full events with HypoDD origins associated to them, C) something else entirely?

Thanks,
Chet

**Comment by luca-s** [comment]
>  B) I still need to run another command (scevent?

This one. I didn't want to include additional logic in `scrtdd` and I preferred to delegate the events creation to `scevent`, since that is what normally a user would do within a seiscomp playback scenario.

```
scevent --ep scrtdd-relocated-origin.xml  > relocated-with-events.xml
```
