### ISSUE TITLE
1.7: airquake issues 

### ISSUE THREAD

**Issue by filefolder** [swiss-seismological-service/scrtdd#60]
congrats on the new release

I notice that exporting/piping a relocated xml now (accidentally?) includes some status updates ("Wrote relocated catalog files..") at the beginning of the file. Is this the correct behaviour and if so how would I avoid this?

e.g. 
`scrtdd --reloc-catalog $csv --ep $xml --profile $profile --author="scrtdd" --verbosity=3 --console=1 -d $conn --xmlout > text.xml`

```
$ head text.hml

Wrote relocated catalog files reloc-event.csv, reloc-phase.csv, reloc-station.csv and cross-correlation results xcorr.csv
<?xml version="1.0" encoding="UTF-8"?>
<seiscomp xmlns="http://geofon.gfz-potsdam.de/ns/seiscomp3-schema/0.12" version="0.12">
  <EventParameters>
```

also (two problems one post sorry), 

I am suddenly getting a very large amount of "out of boundary" errors where once there were none. In the below example the event and station are almost on top of each other and both are well within the horizontal model boundary. Solving normally with NLL works fine. My only guess is there a change in how positive elevations are interpreted  but I really have no idea why this would happen.

`20:52:20 [warning] Travel Time Table error: Requested location is out of grid boundaries (xloc 696.91 yloc 682.47 zloc -29.51 - grid /data/NLL/swaus/swaus.S.SWNNE.time.hdr origx -2.500 origy -2.500 origz -2.500 dx 5.00 dy 5.00 dz 5.00 numx 346 numy 276 numz 61) (Event lat -33.357789 lon 117.009361 depth -29.506220 Station lat -33.284424 lon 117.030300 elevation 240 )`

```
346 276 61  -2.500000 -2.500000 -2.500000  5.000000 5.000000 5.000000 SLOW_LEN FLOAT
TRANSFORM  SIMPLE  LatOrig -39.500000  LongOrig 109.500000  RotCW 0.000000
```

**Comment by luca-s** [comment]
I pushed a fix for the xml catalog that erroneusly contains the application logs.

Regarding the air-quakes issue I have to probably add an option to restore the previous behaviour. However, please let me know how it goes for you if you extend your grid above the ground level.

**Comment by filefolder** [comment]
Thanks for getting to this so quickly. Can confirm that both solutions now work without error. 

However all the air quake events (typically with depth -0.1 or so) are now just skipped over, which is not ideal. I (think) I have constructed my NLL model to have Z origin of -2.5 (see hdr file output in original post) so in theory it should already be able handle anything up to an elevation of 2.5 km without issue.  

Perhaps in addition, I wonder if something similar to NLL's LOCELEVCORR could be implemented so that anything extending above the model (e.g. 2.6 km) is assigned a default p/s velocity. This is also set in my NLL conf file so could just be read from there if needed, but not sure how non-NLL models would work.

**Comment by luca-s** [comment]
It looks like everything work now for you, did I understand it correctly? 

I like the idea of an option similar to NLL's LOCELEVCORR, but I do not plan to work on this soon.

**Comment by luca-s** [comment]
> edit: I have since gone back to the original setting; some events with very large altitudes (> 10 km) are obviously bad to begin with so I don't really mind if they are removed. I might make this the default setting as it seems the most sensible.

So,`resetAirQuakes` disabled or enabled by default?

**Comment by filefolder** [comment]
sorry I wasn't clear--

All bugs are fixed for me but I think there is a potential problem with how "resetAirQuakes" is implemented. Currently it skips any event containing a negative height even if one's NLL model has a negative Z origin which allows this. So in my case, it should still let events with an altitude < 2.5km pass because my model has valid velocities there. 

I would recommend that it is disabled by default (let people see the errors themselves and consider adjusting their model if there are too many), but more importantly also set it so it only removes events with heights which are beyond the range of the model (Z < -2.5) and not necessarily anything above the surface (Z < 0). This may also require a slight rewording in the xml, perhaps something like "_Air-quakes are events whose depth shifts above and beyond the range of the velocity model (typically Z=0) during the inversion. If this option is enabled, relocations where this occurs are skipped._" (or something...)

If that were the behaviour, I would then enable the setting on my data because it would be good QC. Most of what I'm seeing where the relocations are at altitudes at -10 or -20 I am happy to be rejected, but the ones that are just -0.1 or -0.2 are likely good events.

**Comment by filefolder** [comment]
Could also simply implement a "maximum event altitude" parameter to reject all origins which are relocated above a certain height.

**Comment by luca-s** [comment]
> I would recommend that it is disabled by default (let people see the errors themselves and consider adjusting their model if there are too many),

Sounds good to me

> , but more importantly also set it so it only removes events with heights which are beyond the range of the model (Z < -2.5) and not necessarily anything above the surface (Z < 0). 

Good point. I have to add a parameter where the threshold can be specified by the user. With NLL grids I could compute that value automatically, but that doesn't apply to the other travel time table formats (LOCSAT and libtau). So for the sake of consistency I'll let the users specify it.

> Could also simply implement a "maximum event altitude" parameter to reject all origins which are relocated above a certain height.

I don't know that is required. Even with current code those origins will not be successfully relocated and the users will notice that and discard them.

**Comment by luca-s** [comment]
The following configuration should be able to handle the various use cases:

![image](https://user-images.githubusercontent.com/15273575/161986216-c1217959-cf7b-411e-8c8c-dc7bbbe469f2.png)

@filefolder what you think?

**Comment by filefolder** [comment]
i think that just about covers it! Thanks for all this.

**Comment by luca-s** [comment]
I pushed the change. If you feel like trying the new settings on your data I would appreciate your feedback.

**Comment by filefolder** [comment]
FWIW just getting to this data now with limit at 2000m and action RESET_DEPTH and the settings work as expected. Thanks again.

**Comment by luca-s** [comment]
Thanks a lot for letting me know and for the useful discussion on the airquakes handling
