### ISSUE TITLE
1.7: magnitudes calculated only on HH channels

### ISSUE THREAD

**Issue by filefolder** [swiss-seismological-service/scrtdd#61]
It seems like a new feature in 1.7 is that the scrtdd will now call scamp/mag etc to calculate and apply magnitudes during processing(?). This is very welcome and saves me the trouble of having to do them all separately later (but others may not want this?)

However I notice that ONLY HH channel stations are calculated. I am not sure why this would be or if this is even a scrtdd setting or not. Calculating magnitudes the normal way of course works on all channels (e.g. HH, CH, BH, EH) so I am not sure what the difference might be. 

(I realize calculating magnitudes is well beyond the scope of scrtdd is designed but figured I may as well ask)

**Comment by luca-s** [comment]
There is a not documented behaviour of `scrtdd` where the relocated origins inherit the magnitude from the source origin (the one before relocation), but only if the source origin is  **manual** . This is useful to save time of the users that have already spent time properly computing and verifying event magnitudes. 

Is it possible that you are talking about this feature? However this was implemented even in earlier releases.

**Comment by filefolder** [comment]
I am not quite sure;

The data I am relocating is a prelim catalog with "dummy magnitudes" of 1.0 mb. Using version 1.6, there would be no magnitude changes to the catalog, just position changes as expected. I would run scamp/scmag later to get these.

Now in version 1.7, I see that magnitudes are somehow actually being calculated during the scrtdd call (both MLv and a MLa plugin I am using) but ONLY for the HH channel stations. So, not the same 1.0 dummy values but 0.7, 2.3, etc. Actual values. I have browsed through the code and don't know why or how this is happening. Not an issue at all, just curious if this was a purposeful change and if so, how to get it to do all the channels.

**Comment by luca-s** [comment]
I am closing this, but feel free to re-open it whether there more to add to this discussion
