### ISSUE TITLE
Pre-compiled binaries for Ubuntu 22.04

### ISSUE THREAD

**Issue by cjhopp** [swiss-seismological-service/scrtdd#69]
Hi Luca,

Just a quick question (or maybe a couple): Do you know if there are plans to release precompiled binaries for scrtdd on Ubuntu 22.04? I'm getting

`scrtdd: error while loading shared libraries: libboost_program_options.so.1.71.0: cannot open shared object file: No such file or directory`

where libboost is now only available as 1.74 in apt on 22.04. If this is a gempa request, I'll take my question over there!

I'd like to avoid recompiling everything from source if possible, but if that's not necessary, I'm all ears.

Thanks,
Chet

**Comment by luca-s** [comment]
That is strange. I always compile from sources so I didn't notice the package for ubuntu 22.04 was missing. There must have been an error in the automatic package generation. I will ask gempa what went wrong so we will get a new package soon. Thanks for reporting.

**Comment by cjhopp** [comment]
Great, thanks Luca!

**Comment by gempa-jabe** [comment]
Ubuntu 22.04 has been uploaded. We had disabled it because earlier versions did not compile.

FYI, scrtdd does not compile for RHEL7:

```
error: invalid use of incomplete type ‘struct std::hash<HDD::Catalog::Phase::Type>’
```

If that will ever become important, you have been informed ;)

**Comment by luca-s** [comment]
Thanks a lot @gempa-jabe. Duly noted :)
