### ISSUE TITLE
Configure scrtdd in scconfig

### ISSUE THREAD

**Issue by akasa-denada** [swiss-seismological-service/scrtdd#71]
Hi Luca, I missed something. Currently, I had successfully compiled scrtdd in seiscompv6 but I do not see scrtdd in scconfig. Can you help me? And how to compile only [scrtdd](https://data.gempa.de/packages/Public/scrtdd/6/ubuntu/22.04/x86_64) without seiscomp like in this link?

**Comment by luca-s** [comment]
If you don't see that on scconfig there is definitely an error in your compilation and installation procedure. When you `make install` check where the scrtdd related files are being installed, that should give you a hint at the problem. In particular you need `seiscomp/etc/descriptions/scrtdd.xml` to make the configuration visible in scconfig.

> And how to compile only [scrtdd](https://data.gempa.de/packages/Public/scrtdd/6/ubuntu/22.04/x86_64) without seiscomp like in this link?

That code still needs SeisComP to work. it is compiled with seiscomp, distributed separately, but works with seiscomp.
